# Generated by Django 3.2.4 on 2023-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='favorite_sports',
            field=models.ManyToManyField(blank=True, related_name='athletes', to='gym.SportType', verbose_name='ورزش\u200cهای مورد علاقه'),
        ),
    ]
