# Generated by Django 3.2.4 on 2022-05-15 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import sms.models.sms_verification
import utility.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymtimeLookupSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('state', models.CharField(choices=[('CANCELLED', 'ارسالش کنسل شده'), ('CREATED', 'ساخته شده'), ('AWAITING_SENDING', 'در انتظار ارسال'), ('SENT', 'ارسال شده')], default='AWAITING_SENDING', max_length=16, verbose_name='منظور استفاده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('gymtime_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('service_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('phone_number', models.CharField(max_length=32, verbose_name='شماره همراه')),
            ],
            options={
                'verbose_name': 'پیامک احراز هویت',
                'verbose_name_plural': 'پیامک\u200cهای احراز هویت',
            },
            bases=(utility.mixins.StatefulModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GymtimeOfflineSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'لاگ پیامک آفلاین جیم\u200cتایم',
                'verbose_name_plural': 'لاگ\u200cهای پیامک\u200cهای آفلاین جیم\u200cتایم',
            },
        ),
        migrations.CreateModel(
            name='GymtimeSimpleSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('state', models.CharField(choices=[('CANCELLED', 'ارسالش کنسل شده'), ('CREATED', 'ساخته شده'), ('AWAITING_SENDING', 'در انتظار ارسال'), ('SENT', 'ارسال شده')], default='AWAITING_SENDING', max_length=16, verbose_name='منظور استفاده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('gymtime_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('service_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('message', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'verbose_name': 'پیامک معمولی',
                'verbose_name_plural': 'پیامک\u200cهای معمولی',
            },
            bases=(utility.mixins.StatefulModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GymtimeSMS',
            fields=[
                ('gymtimesimplesms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.gymtimesimplesms')),
            ],
            options={
                'verbose_name': 'پیامک جیم\u200cتایم',
                'verbose_name_plural': 'پیامک\u200cهای جیم\u200cتایم',
            },
            bases=('sms.gymtimesimplesms',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('gymtimelookupsms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.gymtimelookupsms')),
                ('token', models.CharField(default=sms.models.sms_verification.generate_token, max_length=8, verbose_name='کد')),
                ('usage_type', models.CharField(choices=[('LOGIN', 'ورود'), ('SIGNUP', 'ثبت نام')], max_length=16, verbose_name='منظور استفاده')),
                ('account_type', models.CharField(choices=[('ATHLETE', 'ورزشکار'), ('GYM_OWNER', 'صاحب ورزشگاه')], max_length=16, verbose_name='نوع اکانت')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده؟')),
            ],
            options={
                'verbose_name': 'تایید صلاحیت SMS',
                'verbose_name_plural': 'تایید صلاحیت SMS',
            },
            bases=('sms.gymtimelookupsms',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSMSVerification',
            fields=[
                ('gymtimelookupsms_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='sms.gymtimelookupsms')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('state', models.CharField(choices=[('CANCELLED', 'ارسالش کنسل شده'), ('CREATED', 'ساخته شده'), ('AWAITING_SENDING', 'در انتظار ارسال'), ('SENT', 'ارسال شده')], default='AWAITING_SENDING', max_length=16, verbose_name='منظور استفاده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('gymtime_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('service_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('phone_number', models.CharField(max_length=32, verbose_name='شماره همراه')),
                ('token', models.CharField(default=sms.models.sms_verification.generate_token, max_length=8, verbose_name='کد')),
                ('usage_type', models.CharField(choices=[('LOGIN', 'ورود'), ('SIGNUP', 'ثبت نام')], max_length=16, verbose_name='منظور استفاده')),
                ('account_type', models.CharField(choices=[('ATHLETE', 'ورزشکار'), ('GYM_OWNER', 'صاحب ورزشگاه')], max_length=16, verbose_name='نوع اکانت')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده؟')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical تایید صلاحیت SMS',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGymtimeSMS',
            fields=[
                ('gymtimesimplesms_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='sms.gymtimesimplesms')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('state', models.CharField(choices=[('CANCELLED', 'ارسالش کنسل شده'), ('CREATED', 'ساخته شده'), ('AWAITING_SENDING', 'در انتظار ارسال'), ('SENT', 'ارسال شده')], default='AWAITING_SENDING', max_length=16, verbose_name='منظور استفاده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('gymtime_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('service_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical پیامک جیم\u200cتایم',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGymtimeSimpleSMS',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('state', models.CharField(choices=[('CANCELLED', 'ارسالش کنسل شده'), ('CREATED', 'ساخته شده'), ('AWAITING_SENDING', 'در انتظار ارسال'), ('SENT', 'ارسال شده')], default='AWAITING_SENDING', max_length=16, verbose_name='منظور استفاده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('gymtime_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('service_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical پیامک معمولی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGymtimeLookupSMS',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('state', models.CharField(choices=[('CANCELLED', 'ارسالش کنسل شده'), ('CREATED', 'ساخته شده'), ('AWAITING_SENDING', 'در انتظار ارسال'), ('SENT', 'ارسال شده')], default='AWAITING_SENDING', max_length=16, verbose_name='منظور استفاده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('gymtime_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('service_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('phone_number', models.CharField(max_length=32, verbose_name='شماره همراه')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical پیامک احراز هویت',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GymtimeSMSReceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('phone_number', models.CharField(max_length=32, verbose_name='شماره همراه')),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptors_set', to='sms.gymtimesms', verbose_name='پیامک مربوطه')),
            ],
            options={
                'verbose_name': 'گیرنده پیامک جیم\u200cتایم',
                'verbose_name_plural': 'گیرندگان پیامک جیم\u200cتایم',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
