version: '3.7'

services:
  gymtime_django:
    container_name: gymtime_backend
    build:
      context: .
    command: uwsgi --http :8000 --module gymtime_backend.wsgi
    ports:
      - "8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - ./:/app

  nginx:
    container_name: gymtimex
    restart: always
    image: nginx:1.20.0
    ports:
      - "80"
    depends_on:
      - gymtime_django
    volumes:
      - ./static/:/static/
      - ./media/:/media/
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    container_name: gymtime_gres
    restart: always
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /home/postgres/gymtime_gres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: gymtime_mq
    ports:
      - "15672"
      - "5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    restart: always

  redis:
    image: "redis:6.2-alpine"
    container_name: gymtime_redis
    ports:
      - "6379"
    restart: always