TRANSACTION_TYPE_WITHDRAW = 'WITHDRAW'
TRANSACTION_TYPE_DEPOSIT = 'DEPOSIT'

TRANSACTION_TYPES = (
    (TRANSACTION_TYPE_WITHDRAW, 'برداشت'),
    (TRANSACTION_TYPE_DEPOSIT, 'واریز'),
)

MANUAL_TRANSACTION_TYPE_WITHDRAW_REQUEST = 'WITHDRAW_REQUEST'
MANUAL_TRANSACTION_TYPE_CHARGE_REQUEST = 'CHARGE_REQUEST'
MANUAL_TRANSACTION_TYPES = (
    (MANUAL_TRANSACTION_TYPE_WITHDRAW_REQUEST, 'درخواست برداشت'),
    (MANUAL_TRANSACTION_TYPE_CHARGE_REQUEST, 'درخواست شارژ')
)

MANUAL_TRANSACTION_STATE_PENDING = 'PENDING'
MANUAL_TRANSACTION_STATE_ACCEPTED = 'ACCEPTED'
MANUAL_TRANSACTION_STATE_REJECTED = 'REJECTED'
MANUAL_TRANSACTION_STATES = (
    (MANUAL_TRANSACTION_STATE_PENDING, 'در حال انتظار'),
    (MANUAL_TRANSACTION_STATE_ACCEPTED, 'تایید شده'),
    (MANUAL_TRANSACTION_STATE_REJECTED, 'رد شده'),
)
