CRM_TASK_STATE_NOT_SEEN = 'NOT_SEEN'
CRM_TASK_STATE_PENDING = 'PENDING'
CRM_TASK_STATE_RESOLVED = 'RESOLVED'

CRM_TASK_STATES = (
    (CRM_TASK_STATE_NOT_SEEN, 'دیده نشده'),
    (CRM_TASK_STATE_PENDING, 'در حال بررسی'),
    (CRM_TASK_STATE_RESOLVED, 'انجام شده'),
)

TICKET_STATE_NOT_SEEN = 'NOT_SEEN'
TICKET_STATE_PENDING = 'PENDING'
TICKET_STATE_ANSWERED = 'ANSWERED'

TICKET_STATES = (
    (TICKET_STATE_NOT_SEEN, 'دیده نشده'),
    (TICKET_STATE_PENDING, 'در حال بررسی'),
    (TICKET_STATE_ANSWERED, 'پاسخ داده شده'),
)

CRM_TASK_TYPE_PAY_OR_PAYBACK_SCHEDULED_SESSION_TO_GYM_OWNER_NAME = 'PAY_TO_GYM_OWNER'
CRM_TASK_TYPE_PAY_OR_PAYBACK_SCHEDULED_SESSION_TO_GYM_OWNER_TITLE = 'تسویه حساب با صاحب ورزشگاه'
CRM_TASK_TYPE_PAY_OR_PAYBACK_SCHEDULED_SESSION_TO_GYM_OWNER_TEMPLATE = 'pay_scheduled_session_to_gym_owner'

CRM_TASK_TYPE_PAYBACK_RESERVATION_TO_ATHLETE_NAME = 'PAYBACK_RESERVATION_TO_ATHLETE'
CRM_TASK_TYPE_PAYBACK_RESERVATION_TO_ATHLETE_TITLE = 'بازگرداندن پول رزرو به ورزشکار'
CRM_TASK_TYPE_PAYBACK_RESERVATION_TO_ATHLETE_TEMPLATE = 'payback_reservation_to_athlete'

CRM_TASK_TYPES = (
    (
        CRM_TASK_TYPE_PAY_OR_PAYBACK_SCHEDULED_SESSION_TO_GYM_OWNER_NAME,
        CRM_TASK_TYPE_PAY_OR_PAYBACK_SCHEDULED_SESSION_TO_GYM_OWNER_TITLE,
        CRM_TASK_TYPE_PAY_OR_PAYBACK_SCHEDULED_SESSION_TO_GYM_OWNER_TEMPLATE,
    ), (
        CRM_TASK_TYPE_PAYBACK_RESERVATION_TO_ATHLETE_NAME,
        CRM_TASK_TYPE_PAYBACK_RESERVATION_TO_ATHLETE_TITLE,
        CRM_TASK_TYPE_PAYBACK_RESERVATION_TO_ATHLETE_TEMPLATE,
    )
)
