# Generated by Django 3.2.4 on 2022-05-15 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import utility.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('code', models.CharField(max_length=32, verbose_name='کد تخفیف')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountPricingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
            ],
            options={
                'verbose_name': 'نوع قیمت\u200cگذاری تخفیف',
                'verbose_name_plural': 'انواع قیمت\u200cگذاری تخفیف',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FixedDiscountPricingType',
            fields=[
                ('discountpricingtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discount.discountpricingtype')),
                ('discount_amount', models.PositiveIntegerField(verbose_name='مقدار تخفیف')),
            ],
            options={
                'verbose_name': 'نوع قیمت\u200cگذاری ثابت تخفیف',
                'verbose_name_plural': 'انواع قیمت\u200cگذاری ثابت تخفیف',
            },
            bases=('discount.discountpricingtype',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PercentageDiscountPricingType',
            fields=[
                ('discountpricingtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discount.discountpricingtype')),
                ('discount_percentage_amount', utility.models.PercentageField(verbose_name='درصد تخفیف')),
                ('maximum_discount_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر مقدار تخفیف')),
            ],
            options={
                'verbose_name': 'نوع قیمت\u200cگذاری درصدی تخفیف',
                'verbose_name_plural': 'انواع قیمت\u200cگذاری درصدی تخفیف',
            },
            bases=('discount.discountpricingtype',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TextDiscountRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('field', models.CharField(choices=[('scheduled_session.gymnasium.type', 'نوع ورزشگاه'), ('gym_usage.type', 'نوع ورزش')], max_length=1024, verbose_name='فیلد مورد نظر')),
                ('operator_function_name', models.CharField(choices=[('eq', 'برابر'), ('ne', 'نابرابر'), ('contains', 'شامل')], max_length=16, verbose_name='نام تابع عملگر')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'محدودیت تخفیف متنی',
                'verbose_name_plural': 'محدودیت\u200cهای تخفیف متنی',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IntegerDiscountRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('value', models.IntegerField(verbose_name='مقدار')),
                ('field', models.CharField(choices=[('scheduled_session.gymnasium.gym_complex_id', 'آیدی مجموعه ورزشی'), ('scheduled_session.gymnasium_id', 'آیدی سالن'), ('scheduled_session.price', 'قیمت سانس'), ('repeats', 'تکرار استفاده')], max_length=1024, verbose_name='فیلد مورد نظر')),
                ('operator_function_name', models.CharField(choices=[('eq', 'برابر'), ('ne', 'نابرابر'), ('lt', 'کمتر از'), ('le', 'کمتر از یا برابر'), ('gt', 'بزرگتر از'), ('ge', 'بزرگتر از یا برابر')], max_length=16, verbose_name='نام تابع عملگر')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'محدودیت تخفیف عددی',
                'verbose_name_plural': 'محدودیت\u200cهای تخفیف عددی',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTextDiscountRestriction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('field', models.CharField(choices=[('scheduled_session.gymnasium.type', 'نوع ورزشگاه'), ('gym_usage.type', 'نوع ورزش')], max_length=1024, verbose_name='فیلد مورد نظر')),
                ('operator_function_name', models.CharField(choices=[('eq', 'برابر'), ('ne', 'نابرابر'), ('contains', 'شامل')], max_length=16, verbose_name='نام تابع عملگر')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('discount', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='discount.discount', verbose_name='تخفیف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical محدودیت تخفیف متنی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPercentageDiscountPricingType',
            fields=[
                ('discountpricingtype_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='discount.discountpricingtype')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('discount_percentage_amount', utility.models.PercentageField(verbose_name='درصد تخفیف')),
                ('maximum_discount_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر مقدار تخفیف')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical نوع قیمت\u200cگذاری درصدی تخفیف',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIntegerDiscountRestriction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('value', models.IntegerField(verbose_name='مقدار')),
                ('field', models.CharField(choices=[('scheduled_session.gymnasium.gym_complex_id', 'آیدی مجموعه ورزشی'), ('scheduled_session.gymnasium_id', 'آیدی سالن'), ('scheduled_session.price', 'قیمت سانس'), ('repeats', 'تکرار استفاده')], max_length=1024, verbose_name='فیلد مورد نظر')),
                ('operator_function_name', models.CharField(choices=[('eq', 'برابر'), ('ne', 'نابرابر'), ('lt', 'کمتر از'), ('le', 'کمتر از یا برابر'), ('gt', 'بزرگتر از'), ('ge', 'بزرگتر از یا برابر')], max_length=16, verbose_name='نام تابع عملگر')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('discount', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='discount.discount', verbose_name='تخفیف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical محدودیت تخفیف عددی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFixedDiscountPricingType',
            fields=[
                ('discountpricingtype_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='discount.discountpricingtype')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('discount_amount', models.PositiveIntegerField(verbose_name='مقدار تخفیف')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical نوع قیمت\u200cگذاری ثابت تخفیف',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDiscountPricingType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical نوع قیمت\u200cگذاری تخفیف',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDiscount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('code', models.CharField(max_length=32, verbose_name='کد تخفیف')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pricing_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='discount.discountpricingtype', verbose_name='نحوه قیمت\u200cگذاری')),
            ],
            options={
                'verbose_name': 'historical تخفیف',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDateTimeDiscountRestriction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('value', models.DateTimeField(verbose_name='مقدار')),
                ('field', models.CharField(choices=[('now', 'زمان پرداخت'), ('scheduled_session.start_datetime', 'زمان شروع سانس')], max_length=1024, verbose_name='فیلد مورد نظر')),
                ('operator_function_name', models.CharField(choices=[('lt', 'کمتر از'), ('le', 'کمتر از یا برابر'), ('gt', 'بزرگتر از'), ('ge', 'بزرگتر از یا برابر')], max_length=16, verbose_name='نام تابع عملگر')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('discount', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='discount.discount', verbose_name='تخفیف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical محدودیت تخفیف زمانی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBooleanDiscountRestriction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('value', models.BooleanField(verbose_name='مقدار')),
                ('field', models.CharField(choices=[], max_length=1024, verbose_name='فیلد مورد نظر')),
                ('operator_function_name', models.CharField(choices=[('eq', 'برابر'), ('ne', 'نابرابر')], max_length=16, verbose_name='نام تابع عملگر')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('discount', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='discount.discount', verbose_name='تخفیف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical محدودیت تخفیف منطقی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='discount',
            name='pricing_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='discount', to='discount.discountpricingtype', verbose_name='نحوه قیمت\u200cگذاری'),
        ),
        migrations.CreateModel(
            name='DateTimeDiscountRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('value', models.DateTimeField(verbose_name='مقدار')),
                ('field', models.CharField(choices=[('now', 'زمان پرداخت'), ('scheduled_session.start_datetime', 'زمان شروع سانس')], max_length=1024, verbose_name='فیلد مورد نظر')),
                ('operator_function_name', models.CharField(choices=[('lt', 'کمتر از'), ('le', 'کمتر از یا برابر'), ('gt', 'بزرگتر از'), ('ge', 'بزرگتر از یا برابر')], max_length=16, verbose_name='نام تابع عملگر')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'محدودیت تخفیف زمانی',
                'verbose_name_plural': 'محدودیت\u200cهای تخفیف زمانی',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BooleanDiscountRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('value', models.BooleanField(verbose_name='مقدار')),
                ('field', models.CharField(choices=[], max_length=1024, verbose_name='فیلد مورد نظر')),
                ('operator_function_name', models.CharField(choices=[('eq', 'برابر'), ('ne', 'نابرابر')], max_length=16, verbose_name='نام تابع عملگر')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'محدودیت تخفیف منطقی',
                'verbose_name_plural': 'محدودیت\u200cهای تخفیف منطقی',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
