

ACCOUNT_TYPE_ATHLETE = 'ATHLETE'
ACCOUNT_TYPE_GYM_OWNER = 'GYM_OWNER'

ACCOUNT_TYPES = (
    (ACCOUNT_TYPE_ATHLETE, 'ورزشکار'),
    (ACCOUNT_TYPE_GYM_OWNER, 'صاحب ورزشگاه'),
)

ATHLETE_GENDER_MALE = 'MALE'
ATHLETE_GENDER_FEMALE = 'FEMALE'

ATHLETE_GENDERS = (
    (ATHLETE_GENDER_MALE, 'مرد'),
    (ATHLETE_GENDER_FEMALE, 'زن')
)
