INTEGER_RESTRICTION_FIELD_GYM_COMPLEX_ID = 'scheduled_session.gymnasium.gym_complex_id'
INTEGER_RESTRICTION_FIELD_GYMNASIUM_ID = 'scheduled_session.gymnasium_id'
INTEGER_RESTRICTION_FIELD_SCHEDULED_SESSION_PRICE = 'scheduled_session.price'
INTEGER_RESTRICTION_FIELD_REPEATS = 'repeats'

INTEGER_RESTRICTION_FIELD_CHOICES = (
    (INTEGER_RESTRICTION_FIELD_GYM_COMPLEX_ID, 'آیدی مجموعه ورزشی'),
    (INTEGER_RESTRICTION_FIELD_GYMNASIUM_ID, 'آیدی سالن'),
    (INTEGER_RESTRICTION_FIELD_SCHEDULED_SESSION_PRICE, 'قیمت سانس'),
    (INTEGER_RESTRICTION_FIELD_REPEATS, 'تکرار استفاده'),
)


DATETIME_RESTRICTION_FIELD_NOW = 'now'
DATETIME_RESTRICTION_FIELD_SCHEDULED_SESSION_START_DATETIME = 'scheduled_session.start_datetime'
DATETIME_RESTRICTION_FIELD_CHOICES = (
    (DATETIME_RESTRICTION_FIELD_NOW, 'زمان پرداخت'),
    (DATETIME_RESTRICTION_FIELD_SCHEDULED_SESSION_START_DATETIME, 'زمان شروع سانس')
)


TEXT_RESTRICTION_FIELD_GYMNASIUM_TYPE = 'scheduled_session.gymnasium.type'
TEXT_RESTRICTION_FIELD_GYM_USAGE_TYPE = 'gym_usage.type'

TEXT_RESTRICTION_FIELD_CHOICES = (
    (TEXT_RESTRICTION_FIELD_GYMNASIUM_TYPE, 'نوع ورزشگاه'),
    (TEXT_RESTRICTION_FIELD_GYM_USAGE_TYPE, 'نوع ورزش'),
)

BOOLEAN_RESTRICTION_FIELD_CHOICES = ()
