# Generated by Django 3.2.4 on 2022-05-15 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import gym.models.gym_complex
import gym.models.gym_content_media
import simple_history.models
import utility.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
        ('discount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
            ],
            options={
                'verbose_name': 'باشگاه مخاطبین',
                'verbose_name_plural': 'باشگاه\u200cهای مخاطبین',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClubContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('full_name', models.CharField(max_length=256, verbose_name='نام کامل')),
                ('phone_number', models.CharField(max_length=32, verbose_name='شماره همراه')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_contacts', to='account.athlete', verbose_name='مجموعه ورزشی مربوطه')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='gym.club', verbose_name='باشگاه مخاطبین مربوطه')),
            ],
            options={
                'verbose_name': 'مخاطب باشگاه',
                'verbose_name_plural': 'مخاطبین باشگاه',
                'unique_together': {('club', 'phone_number')},
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClubDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discount.discount')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.club', verbose_name='باشگاه مخاطبین مربوطه')),
                ('contacts', models.ManyToManyField(to='gym.ClubContact', verbose_name='مخاطبین')),
            ],
            options={
                'verbose_name': 'تخفیف باشگاه مخاطبین',
                'verbose_name_plural': 'تخفیف\u200cهای باشگاه\u200cهای مخاطبین',
            },
            bases=('discount.discount', models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClubSMS',
            fields=[
                ('gymtimesimplesms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms.gymtimesimplesms')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.club', verbose_name='باشگاه مخاطبین مربوطه')),
                ('contacts', models.ManyToManyField(to='gym.ClubContact', verbose_name='مخاطبین')),
            ],
            options={
                'verbose_name': 'پیامک کلاب',
                'verbose_name_plural': 'پیامک\u200cهای کلاب',
            },
            bases=('sms.gymtimesimplesms', models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GymComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('code', models.CharField(db_index=True, default=gym.models.gym_complex.generate_gym_complex_code, max_length=10, unique=True, verbose_name='کد مجموعه ورزشی')),
                ('phone_number', models.CharField(max_length=32, verbose_name='شماره تماس مجموعه')),
                ('name', models.CharField(max_length=128, verbose_name='نام مجموعه')),
                ('address', models.TextField(verbose_name='آدرس متنی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='قوانین')),
                ('instagram_username', models.CharField(blank=True, max_length=256, null=True, verbose_name='آیدی اینستاگرام مجموعه ورزشی')),
            ],
            options={
                'verbose_name': 'مجموعه ورزشی',
                'verbose_name_plural': 'مجموعه\u200cهای ورزشی',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GymContentMediaInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Gymnasium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('gym_owner_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ پرداختی به صاحب ورزشگاه')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='قوانین')),
                ('attachments_interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gym.gymcontentmediainterface', verbose_name='پیوست\u200cها')),
                ('gym_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gymnasiums', to='gym.gymcomplex', verbose_name='مجموعه مربوطه')),
            ],
            options={
                'verbose_name': 'ورزشگاه',
                'verbose_name_plural': 'ورزشگاه\u200cها',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GymnasiumType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=256, unique=True, verbose_name='عنوان فارسی')),
            ],
            options={
                'verbose_name': 'نوع ورزشگاه',
                'verbose_name_plural': 'انواع ورزشگاه',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GymUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('gymnasium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_usages', to='gym.gymnasium', verbose_name='ورزشگاه مربوطه')),
            ],
            options={
                'verbose_name': 'کاربری ورزشگاه',
                'verbose_name_plural': 'کاربری\u200cهای ورزشگاه',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=256, unique=True, verbose_name='عنوان فارسی')),
            ],
            options={
                'verbose_name': 'نوع ورزش',
                'verbose_name_plural': 'انواع ورزش',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('start_datetime', models.DateTimeField(verbose_name='زمان شروع سانس')),
                ('end_datetime', models.DateTimeField(verbose_name='زمان پایان سانس')),
                ('state', models.CharField(choices=[('AVAILABLE', 'دردسترس'), ('PENDING', 'در حال انتظار'), ('RESERVED', 'رزرو شده'), ('CANCELLED', 'کنسل شده')], default='AVAILABLE', max_length=128, verbose_name='وضعیت')),
                ('price', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('gym_owner_price', models.PositiveIntegerField(verbose_name='مبلغ پرداختی به صاحب ورزشگاه')),
                ('gymnasium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_sessions', to='gym.gymnasium', verbose_name='ورزشگاه مربوطه')),
            ],
            options={
                'verbose_name': 'سانس ورزشگاه',
                'verbose_name_plural': 'سانس\u200cهای ورزشگاه',
            },
            bases=(utility.mixins.StatefulModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalScheduledSession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('start_datetime', models.DateTimeField(verbose_name='زمان شروع سانس')),
                ('end_datetime', models.DateTimeField(verbose_name='زمان پایان سانس')),
                ('state', models.CharField(choices=[('AVAILABLE', 'دردسترس'), ('PENDING', 'در حال انتظار'), ('RESERVED', 'رزرو شده'), ('CANCELLED', 'کنسل شده')], default='AVAILABLE', max_length=128, verbose_name='وضعیت')),
                ('price', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('gym_owner_price', models.PositiveIntegerField(verbose_name='مبلغ پرداختی به صاحب ورزشگاه')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gymnasium', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.gymnasium', verbose_name='ورزشگاه مربوطه')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical سانس ورزشگاه',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGymUsage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gymnasium', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.gymnasium', verbose_name='ورزشگاه مربوطه')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.sporttype', verbose_name='نوع ورزش')),
            ],
            options={
                'verbose_name': 'historical کاربری ورزشگاه',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGymnasium',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('gym_owner_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ پرداختی به صاحب ورزشگاه')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='قوانین')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('attachments_interface', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.gymcontentmediainterface', verbose_name='پیوست\u200cها')),
                ('gym_complex', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.gymcomplex', verbose_name='مجموعه مربوطه')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.gymnasiumtype', verbose_name='نوع ورزشگاه')),
            ],
            options={
                'verbose_name': 'historical ورزشگاه',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGymComplex',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('code', models.CharField(db_index=True, default=gym.models.gym_complex.generate_gym_complex_code, max_length=10, verbose_name='کد مجموعه ورزشی')),
                ('phone_number', models.CharField(max_length=32, verbose_name='شماره تماس مجموعه')),
                ('name', models.CharField(max_length=128, verbose_name='نام مجموعه')),
                ('address', models.TextField(verbose_name='آدرس متنی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='قوانین')),
                ('instagram_username', models.CharField(blank=True, max_length=256, null=True, verbose_name='آیدی اینستاگرام مجموعه ورزشی')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('attachments_interface', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.gymcontentmediainterface', verbose_name='پیوست\u200cها')),
                ('club', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.club', verbose_name='باشگاه مخاطبین')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.gymowner', verbose_name='صاحب ورزشگاه')),
            ],
            options={
                'verbose_name': 'historical مجموعه ورزشی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClubSMSForDiscount',
            fields=[
                ('clubsms_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='gym.clubsms')),
                ('gymtimesimplesms_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='sms.gymtimesimplesms')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('state', models.CharField(choices=[('CANCELLED', 'ارسالش کنسل شده'), ('CREATED', 'ساخته شده'), ('AWAITING_SENDING', 'در انتظار ارسال'), ('SENT', 'ارسال شده')], default='AWAITING_SENDING', max_length=16, verbose_name='منظور استفاده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('gymtime_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('service_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('club', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.club', verbose_name='باشگاه مخاطبین مربوطه')),
                ('discount', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.clubdiscount', verbose_name='تخفیف مربوطه')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical پیامک تخفیف کلاب',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClubSMS',
            fields=[
                ('gymtimesimplesms_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='sms.gymtimesimplesms')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('state', models.CharField(choices=[('CANCELLED', 'ارسالش کنسل شده'), ('CREATED', 'ساخته شده'), ('AWAITING_SENDING', 'در انتظار ارسال'), ('SENT', 'ارسال شده')], default='AWAITING_SENDING', max_length=16, verbose_name='منظور استفاده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('gymtime_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('service_errors', models.TextField(blank=True, null=True, verbose_name='ارورها')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('club', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.club', verbose_name='باشگاه مخاطبین مربوطه')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical پیامک کلاب',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClubDiscount',
            fields=[
                ('discount_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='discount.discount')),
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('code', models.CharField(max_length=32, verbose_name='کد تخفیف')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('club', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.club', verbose_name='باشگاه مخاطبین مربوطه')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pricing_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='discount.discountpricingtype', verbose_name='نحوه قیمت\u200cگذاری')),
            ],
            options={
                'verbose_name': 'historical تخفیف باشگاه مخاطبین',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClubContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('full_name', models.CharField(max_length=256, verbose_name='نام کامل')),
                ('phone_number', models.CharField(max_length=32, verbose_name='شماره همراه')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('athlete', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.athlete', verbose_name='مجموعه ورزشی مربوطه')),
                ('club', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.club', verbose_name='باشگاه مخاطبین مربوطه')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical مخاطب باشگاه',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GymUsageEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('type', models.CharField(choices=[], max_length=256, verbose_name='نوع تجهیز کاربری ورزشگاه')),
                ('price', models.PositiveIntegerField(verbose_name='پول امکانات')),
                ('gym_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='gym.gymusage', verbose_name='کاربری ورزشگاه مربوطه')),
            ],
            options={
                'verbose_name': 'تجهیز کاربری ورزشگاه',
                'verbose_name_plural': 'تجهیزات کاربری ورزشگاه',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='gymusage',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gym_usages', to='gym.sporttype', verbose_name='نوع ورزش'),
        ),
        migrations.CreateModel(
            name='GymThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('file', models.FileField(upload_to=gym.models.gym_content_media.get_gym_content_media_upload_to, verbose_name='فایل')),
                ('attachments_interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='gym.gymcontentmediainterface', verbose_name='رابط ضمیمه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gymnasiumtype',
            name='sport_types',
            field=models.ManyToManyField(blank=True, related_name='gymnasium_types', to='gym.SportType', verbose_name='انواع ورزش\u200cهای مربوطه'),
        ),
        migrations.AddField(
            model_name='gymnasium',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gymnasiums', to='gym.gymnasiumtype', verbose_name='نوع ورزشگاه'),
        ),
        migrations.CreateModel(
            name='GymContentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('file', models.FileField(upload_to=gym.models.gym_content_media.get_gym_content_media_upload_to, verbose_name='فایل')),
                ('attachments_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='gym.gymcontentmediainterface', verbose_name='رابط ضمیمه')),
            ],
            options={
                'verbose_name': 'عکس ورزشگاه',
                'verbose_name_plural': 'عکس\u200cهای ورزشگاه',
            },
        ),
        migrations.AddField(
            model_name='gymcomplex',
            name='attachments_interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gym.gymcontentmediainterface', verbose_name='پیوست\u200cها'),
        ),
        migrations.AddField(
            model_name='gymcomplex',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gym_complex', to='gym.club', verbose_name='باشگاه مخاطبین'),
        ),
        migrations.AddField(
            model_name='gymcomplex',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_complexes', to='account.gymowner', verbose_name='صاحب ورزشگاه'),
        ),
        migrations.CreateModel(
            name='ClubSMSForDiscount',
            fields=[
                ('clubsms_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.clubsms')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_sms', to='gym.clubdiscount', verbose_name='تخفیف مربوطه')),
            ],
            options={
                'verbose_name': 'پیامک تخفیف کلاب',
                'verbose_name_plural': 'پیامک\u200cهای تخفیف کلاب',
            },
            bases=('gym.clubsms',),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
