# Generated by Django 3.2.4 on 2022-05-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportTypeIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('file', models.FileField(upload_to='sport_icon', verbose_name='فایل')),
                ('sport_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='gym.sporttype', verbose_name='نوع ورزش مربوطه')),
            ],
            options={
                'verbose_name': 'آیکون ورزشی',
                'verbose_name_plural': 'آیکون\u200cهای ورزشی',
            },
        ),
    ]
