# Generated by Django 3.2.4 on 2022-05-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_sporttypeicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymusageequipment',
            name='price',
            field=models.PositiveIntegerField(verbose_name='مبلغ امکانات'),
        ),
    ]
