# Generated by Django 3.2.4 on 2022-06-12 22:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import utility.models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_gymusageequipment_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymnasiumAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=256, unique=True, verbose_name='عنوان فارسی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gymnasium',
            name='length',
            field=utility.models.PositiveFloatField(default=0, help_text='به متر', verbose_name='طول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymnasium',
            name='width',
            field=utility.models.PositiveFloatField(default=0, help_text='به متر', verbose_name='عرض'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgymnasium',
            name='length',
            field=utility.models.PositiveFloatField(default=0, help_text='به متر', verbose_name='طول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgymnasium',
            name='width',
            field=utility.models.PositiveFloatField(default=0, help_text='به متر', verbose_name='عرض'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymcontentmedia',
            name='attachments_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='gym.gymcontentmediainterface', verbose_name='رابط ضمیمه'),
        ),
        migrations.AlterField(
            model_name='gymthumbnail',
            name='attachments_interface',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='gym.gymcontentmediainterface', verbose_name='رابط ضمیمه'),
        ),
        migrations.AlterField(
            model_name='gymusageequipment',
            name='type',
            field=models.CharField(choices=[('BALL', 'توپ')], max_length=256, verbose_name='نوع تجهیز کاربری ورزشگاه'),
        ),
        migrations.CreateModel(
            name='GymComplexNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('nickname', models.CharField(max_length=512, verbose_name='نام مستعار')),
                ('gym_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicknames', to='gym.gymcomplex', verbose_name='مجموعه ورزشی')),
            ],
            options={
                'verbose_name': 'نام مستعار مجموعه ورزشی',
                'verbose_name_plural': 'نام\u200cهای مستعار مجموعه ورزشی',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='gymnasium',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='gymnasiums', to='gym.GymnasiumAttribute', verbose_name='امکانات ورزشگاه'),
        ),
    ]
