# Generated by Django 3.2.4 on 2023-02-06 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import utility.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        ('account', '0001_initial'),
        ('discount', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('state', models.CharField(choices=[('CREATED', 'ساخته شده'), ('PURCHASED', 'پرداخت شده'), ('DONE', 'انجام شده'), ('CANCELLED', 'کنسل شده')], default='PURCHASED', max_length=128, verbose_name='وضعیت')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='account.athlete', verbose_name='ورزشکار')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='discount.discount', verbose_name='تخفیف')),
                ('gym_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='gym.gymusage', verbose_name='کاربری ورزشگاه مربوطه')),
                ('scheduled_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='gym.scheduledsession', verbose_name='سانس مربوطه')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
            },
            bases=(utility.mixins.StatefulModelMixin, models.Model),
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UsedEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('gym_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_equipments', to='gym.gymusageequipment', verbose_name='تجهیز مربوطه')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_equipments', to='reservation.reserve', verbose_name='رزرو مربوطه')),
            ],
            options={
                'verbose_name': 'تجهیز استفاده شده',
                'verbose_name_plural': 'تجهیزات استفاده شده',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUsedEquipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gym_equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.gymusageequipment', verbose_name='تجهیز مربوطه')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reserve', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reservation.reserve', verbose_name='رزرو مربوطه')),
            ],
            options={
                'verbose_name': 'historical تجهیز استفاده شده',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReserve',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('state', models.CharField(choices=[('CREATED', 'ساخته شده'), ('PURCHASED', 'پرداخت شده'), ('DONE', 'انجام شده'), ('CANCELLED', 'کنسل شده')], default='PURCHASED', max_length=128, verbose_name='وضعیت')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('athlete', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.athlete', verbose_name='ورزشکار')),
                ('discount', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='discount.discount', verbose_name='تخفیف')),
                ('gym_usage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.gymusage', verbose_name='کاربری ورزشگاه مربوطه')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheduled_session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gym.scheduledsession', verbose_name='سانس مربوطه')),
            ],
            options={
                'verbose_name': 'historical رزرو',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='آیا حذف شده است؟')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('comment_text', models.TextField(blank=True, null=True, verbose_name='متن نظر')),
                ('reserve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='reservation.reserve', verbose_name='رزرو مربوطه')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
